# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('enunciado', models.TextField()),
                ('entrada', models.TextField(blank=True)),
                ('saida', models.TextField()),
                ('scores', models.IntegerField(default=100)),
                ('tags', models.CharField(default='laços', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('status', models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('JSSintaxError', 'Erro de sintaxe!'), ('JSRuntimeError', 'Erro em execução!'), ('JSTimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default=('Waiting', 'Esperando ser executada.'), max_length=36)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Question')),
            ],
        ),
    ]
