# Generated by Django 2.2 on 2019-04-17 13:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('plataforma', '0001_initial'), ('plataforma', '0002_auto_20170711_1225'), ('plataforma', '0003_auto_20170711_1308'), ('plataforma', '0004_auto_20170712_1232'), ('plataforma', '0005_auto_20170713_1559'), ('plataforma', '0006_auto_20170713_1808'), ('plataforma', '0007_submissionsummary'), ('plataforma', '0008_auto_20170720_1152'), ('plataforma', '0009_perfil'), ('plataforma', '0010_auto_20170809_1219'), ('plataforma', '0011_auto_20180601_0358'), ('plataforma', '0012_auto_20190408_1918')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('entrada', models.TextField(blank=True)),
                ('saida', models.TextField(blank=True)),
                ('xp', models.IntegerField(default=100)),
                ('tags', models.CharField(default='laços', max_length=255)),
                ('pos_codigo', models.TextField(blank=True, default='')),
                ('pre_codigo', models.TextField(blank=True, default="const fs = require('fs')\n\nconst document = {\n  write: function (msg) {\n    console.log(msg)\n  }\n}\n\nfunction alert (msg) {\n  console.log(msg)\n}\n\nfunction prompt (msg) {\n  process.stdin.resume()\n  var buffer = Buffer.alloc(1)\n  var result = ''\n  var bytesRead\n\n  while (true) {\n    bytesRead = 0\n    try {\n      bytesRead = fs.readSync(process.stdin.fd, buffer, 0, 1)\n    } catch (e) {\n      if (e.code === 'EAGAIN') {\n        console.error('ERROR: interactive stdin input not supported.')\n        process.exit(1)\n      } else if (e.code === 'EOF') {\n        break\n      }\n      throw e\n    }\n    if (bytesRead === 0) {\n      break\n    }\n\n    var char = buffer.toString('utf8')\n    if (char === '\\r') {\n      continue\n    } else if (char === '\\n') {\n      break\n    } else {\n      result += char\n    }\n  }\n\n  process.stdin.pause()\n  return result\n}\n\nfunction confirm (msg) {\n  const result = prompt()\n\n  if ((result === 'Sim') || (result === 'sim') || (result === 'S') || (result === 's') ||\n    (result === 'Yes') || (result === 'yes') || (result === 'Y') || (result === 'y') ||\n    (result === 'Ok') || (result === 'ok') || (result === '1')) {\n    return true\n  } else {\n    return false\n  }\n}\n")),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('status', models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('JSSintaxError', 'Erro de sintaxe!'), ('JSRuntimeError', 'Erro em execução!'), ('JSTimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default=('Waiting', 'Esperando ser executada.'), max_length=36)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Question')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TextField(blank=True)),
                ('saida', models.TextField(blank=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Question')),
            ],
        ),
        migrations.RunSQL(
            sql='CREATE VIEW plataforma_submission_summary AS SELECT status, count(*) as sum FROM plataforma_submission GROUP BY status; ',
            reverse_sql='DROP VIEW IF EXISTS plataforma_submission_summary;',
        ),
        migrations.CreateModel(
            name='SubmissionSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('JSSintaxError', 'Erro de sintaxe!'), ('JSRuntimeError', 'Erro em execução!'), ('JSTimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default=('JSSintaxError', 'Erro de sintaxe!'), max_length=36)),
                ('sum', models.IntegerField()),
            ],
            options={
                'db_table': 'plataforma_submission_summary',
                'managed': False,
                'verbose_name': 'Summary of Submission',
                'verbose_name_plural': 'Summary of Submissions',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='plataforma.Tags'),
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='question',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='pos_codigo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pre_codigo',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('unkwon', 'Unkwon'), ('c', 'C'), ('java', 'Java'), ('python', 'Python')], default=('Waiting', 'Esperando ser executada.'), max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('SintaxError', 'Erro de sintaxe!'), ('RuntimeError', 'Erro em execução!'), ('TimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default=('Waiting', 'Esperando ser executada.'), max_length=36),
        ),
    ]
