# Generated by Django 2.2.1 on 2019-05-14 13:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSummary',
            fields=[
                ('status', models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('SintaxError', 'Erro de sintaxe!'), ('RuntimeError', 'Erro em execução!'), ('TimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default='Waiting', max_length=255, primary_key=True, serialize=False)),
                ('sum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Summary of Submission',
                'verbose_name_plural': 'Summary of Submissions',
                'db_table': 'plataforma_submission_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('enunciado', ckeditor.fields.RichTextField()),
                ('entrada', models.TextField(blank=True)),
                ('saida', models.TextField(blank=True)),
                ('xp', models.IntegerField(default=100)),
                ('exibir', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('status', models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('SintaxError', 'Erro de sintaxe!'), ('RuntimeError', 'Erro em execução!'), ('TimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default='Waiting', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('unkwon', 'Unkwon'), ('c', 'C'), ('c++11', 'C++11'), ('javascript', 'JavaScript'), ('java', 'Java'), ('python', 'Python')], default='Waiting', max_length=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Question')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='plataforma.Tags'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CaseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TextField(blank=True)),
                ('saida', models.TextField(blank=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Question')),
            ],
        ),
    ]
