# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('enunciado', models.TextField()),
                ('entrada', models.TextField()),
                ('saida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('status', models.TextField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Questoes')),
            ],
        ),
    ]
