# Generated by Django 2.2.1 on 2019-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubmissionSummary',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
