# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='entrada',
            field=models.TextField(blank=True),
        ),
    ]
