# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TextField(blank=True)),
                ('saida', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='scores',
            new_name='xp',
        ),
        migrations.AlterField(
            model_name='question',
            name='saida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casetest',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.Question'),
        ),
    ]
