# Generated by Django 2.2 on 2019-05-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_squashed_0012_auto_20190408_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['titulo']},
        ),
        migrations.AddField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('unkwon', 'Unkwon'), ('c', 'C'), ('c++11', 'C++11'), ('javascript', 'JavaScript'), ('java', 'Java'), ('python', 'Python')], default=('Waiting', 'Esperando ser executada.'), max_length=10),
        ),
    ]
