# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20170711_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pos_codigo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='pre_codigo',
            field=models.TextField(default=''),
        ),
    ]
