# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20170624_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='questoes',
            name='tags',
            field=models.CharField(default='laços', max_length=255),
        ),
    ]
