# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_questoes_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissoes',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('JSSintaxError', 'Erro de sintaxe!'), ('JSRuntimeError', 'Erro em execução!'), ('JSTimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!')], default=('Waiting', 'Esperando ser executada.'), max_length=36),
        ),
    ]
