# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:59
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_auto_20170712_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='enunciado',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='pos_codigo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='pre_codigo',
            field=models.TextField(blank=True, default="const fs = require('fs')\n\nconst document = {\n  write: function (msg) {\n    console.log(msg)\n  }\n}\n\nfunction alert (msg) {\n  console.log(msg)\n}\n\nfunction prompt (msg) {\n  process.stdin.resume()\n  var buffer = Buffer.alloc(1)\n  var result = ''\n  var bytesRead\n\n  while (true) {\n    bytesRead = 0\n    try {\n      bytesRead = fs.readSync(process.stdin.fd, buffer, 0, 1)\n    } catch (e) {\n      if (e.code === 'EAGAIN') {\n        console.error('ERROR: interactive stdin input not supported.')\n        process.exit(1)\n      } else if (e.code === 'EOF') {\n        break\n      }\n      throw e\n    }\n    if (bytesRead === 0) {\n      break\n    }\n\n    var char = buffer.toString('utf8')\n    if (char === '\\r') {\n      continue\n    } else if (char === '\\n') {\n      break\n    } else {\n      result += char\n    }\n  }\n\n  process.stdin.pause()\n  return result\n}\n\nfunction confirm (msg) {\n  const result = prompt()\n\n  if ((result === 'Sim') || (result === 'sim') || (result === 'S') || (result === 's') ||\n    (result === 'Yes') || (result === 'yes') || (result === 'Y') || (result === 'y') ||\n    (result === 'Ok') || (result === 'ok') || (result === '1')) {\n    return true\n  } else {\n    return false\n  }\n}\n"),
        ),
    ]
