# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_auto_20170713_1559'),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE VIEW IF NOT EXISTS plataforma_submission_summary AS \
            SELECT status, count(*) as sum FROM plataforma_submission GROUP BY status; \
            """,
            """DROP VIEW IF EXISTS plataforma_submission_summary;"""
        )
    ]
