# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_auto_20170713_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSummary',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('JSSintaxError', 'Erro de sintaxe!'), ('JSRuntimeError', 'Erro em execução!'), ('JSTimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default=('JSSintaxError', 'Erro de sintaxe!'), max_length=36)),
                ('sum', models.IntegerField()),
            ],
            options={
                'db_table': 'plataforma_submission_summary',
                'managed': False,
            },
        ),
    ]
