# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_submissionsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionsummary',
            options={'managed': False, 'verbose_name': 'Summary of Submission', 'verbose_name_plural': 'Summary of Submissions'},
        ),
    ]
