# Generated by Django 2.0 on 2018-06-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_auto_20170809_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='question',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pre_codigo',
            field=models.TextField(blank=True, default="const fs = require('fs')\n\nconst document = {\n  write: function (msg) {\n    console.log(msg)\n  }\n}\n\nfunction alert (msg) {\n  console.log(msg)\n}\n\nfunction prompt (msg) {\n  process.stdin.resume()\n  var buffer = Buffer.alloc(1)\n  var result = ''\n  var bytesRead\n\n  while (true) {\n    bytesRead = 0\n    try {\n      bytesRead = fs.readSync(process.stdin.fd, buffer, 0, 1)\n    } catch (e) {\n      if (e.code === 'EAGAIN') {\n        console.error('ERROR: interactive stdin input not supported.')\n        process.exit(1)\n      } else if (e.code === 'EOF') {\n        break\n      }\n      throw e\n    }\n    if (bytesRead === 0) {\n      break\n    }\n\n    var char = buffer.toString('utf8')\n      // Read next byte when char is \\r or result is empty and char is blank (' ', '\\t')\n    if (char === '\\r' || (result.length === 0 && (char === ' ' || char === '\\t'))) {\n      continue\n    } else if (char === '\\n' || char === ' ' || char === '\\t') {\n      break\n    } else {\n      result += char\n    }\n  }\n\n  process.stdin.pause()\n  return result\n}\n\nfunction confirm (msg) {\n  const result = prompt()[0].toLowerCase()\n\n  return ((result === 't') || (result === 's') || (result === 'y') || (result === '1'))\n}\n"),
        ),
    ]
