# Generated by Django 2.2 on 2019-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0011_auto_20180601_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pos_codigo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pre_codigo',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('unkwon', 'Unkwon'), ('c', 'C'), ('java', 'Java'), ('python', 'Python')], default=('Waiting', 'Esperando ser executada.'), max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Esperando ser executada.'), ('SintaxError', 'Erro de sintaxe!'), ('RuntimeError', 'Erro em execução!'), ('TimeoutError', 'Tempo de execução excedido!'), ('DiffError', 'Saída computada diferente da saída esperada!'), ('OK', 'OK')], default=('Waiting', 'Esperando ser executada.'), max_length=36),
        ),
    ]
