# Generated by Django 5.1.2 on 2024-10-29 18:18

import uuid

import django.db.migrations.operations.special
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


def gen_uuid_for_submissions(apps, schema_editor):
    Submission = apps.get_model("core", "Submission")
    for row in Submission.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


def gen_uuid_for_questions(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    for row in Question.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_submission_uuid"),
        ("core", "0003_populate_uuid_values"),
        ("core", "0004_remove_uuid_null"),
        ("core", "0005_submission_log"),
        ("core", "0006_submission_output"),
        ("core", "0007_alter_submission_language"),
        ("core", "0008_achievementpicture_achievement"),
        ("core", "0009_achievement_hidden"),
        ("core", "0010_question_uuid"),
        ("core", "0011_populate_uuid_values"),
        ("core", "0012_alter_question_uuid_unique"),
        ("core", "0013_alter_question_statement"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tags",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("statement", django_ckeditor_5.fields.CKEditor5Field()),
                ("sample_input", models.TextField(blank=True)),
                ("sample_output", models.TextField(blank=True)),
                ("xp", models.IntegerField(default=100)),
                ("visible", models.BooleanField(default=True)),
                ("tags", models.ManyToManyField(to="core.tags")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CaseTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_input", models.TextField(blank=True)),
                ("sample_output", models.TextField(blank=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Esperando ser executada."),
                            ("SintaxError", "Erro de sintaxe!"),
                            ("RuntimeError", "Erro em execução!"),
                            ("TimeoutError", "Tempo de execução excedido!"),
                            (
                                "DiffError",
                                "Saída computada diferente da saída esperada!",
                            ),
                            ("OK", "OK"),
                        ],
                        default="Waiting",
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("unkwon", "Unkwon"),
                            ("c", "C"),
                            ("c++11", "C++11"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("python", "Python"),
                        ],
                        default="Waiting",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_submission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.question",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RunPython(
            code=gen_uuid_for_submissions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="submission",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="output",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("unkwon", "Unkwon"),
                    ("c", "C"),
                    ("c++11", "C++11"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("python", "Python"),
                ],
                default="unkwon",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AchievementPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bytes", models.TextField()),
                ("filename", models.CharField(max_length=255)),
                ("mimetype", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "badge",
                    models.ImageField(
                        upload_to="core.AchievementPicture/bytes/filename/mimetype"
                    ),
                ),
                ("xp", models.IntegerField(default=100)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="uuid",
            ),
        ),
        migrations.RunPython(
            code=gen_uuid_for_questions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="statement",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
