# Generated by Django 2.2.4 on 2019-11-05 11:35

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Submission = apps.get_model("core", "Submission")
    for row in Submission.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_submission_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
