# Generated by Django 2.2.4 on 2019-11-05 11:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
