# Generated by Django 2.2.4 on 2019-12-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_uuid_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="log",
            field=models.TextField(blank=True),
        ),
    ]
