# Generated by Django 2.2.4 on 2019-12-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_submission_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="output",
            field=models.TextField(blank=True),
        ),
    ]
