# Generated by Django 3.2.4 on 2021-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_submission_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("unkwon", "Unkwon"),
                    ("c", "C"),
                    ("c++11", "C++11"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("python", "Python"),
                ],
                default="unkwon",
                max_length=10,
            ),
        ),
    ]
