# Generated by Django 4.2.5 on 2023-09-25 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_alter_submission_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementPicture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bytes", models.TextField()),
                ("filename", models.CharField(max_length=255)),
                ("mimetype", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "badge",
                    models.ImageField(
                        upload_to="core.AchievementPicture/bytes/filename/mimetype"
                    ),
                ),
                ("xp", models.IntegerField(default=100)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="achievements", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
