# Generated by Django 4.2.5 on 2023-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_achievementpicture_achievement"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
