# Generated by Django 5.0.3 on 2024-06-25 03:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_achievement_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="uuid",
            ),
        ),
    ]
