# Generated by Django 5.0.3 on 2024-06-17 22:24

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_alter_user_email"),
        ("core", "0009_achievement_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                ("date_start", models.DateTimeField(verbose_name="Data de Início")),
                ("date_end", models.DateTimeField(verbose_name="Data de Fim")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Descrição"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliações",
            },
        ),
        migrations.CreateModel(
            name="QuestionInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.PositiveIntegerField(verbose_name="Pontuação")),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.assessment",
                        verbose_name="Avaliação",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.question",
                        verbose_name="Questão",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="questions",
            field=models.ManyToManyField(
                through="core.QuestionInfo", to="core.question", verbose_name="Questões"
            ),
        ),
    ]
