# Generated by Django 5.0.3 on 2024-06-25 03:40

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    for row in Question.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_question_uuid"),
    ]

    operations = [
        migrations.RunPython(
            gen_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
