# Generated by Django 5.1.2 on 2024-10-29 17:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_question_uuid_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="statement",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
