# Generated by Django 5.1.2 on 2024-11-30 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_squashed_0013_alter_question_statement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="badge",
            field=models.ImageField(
                upload_to="core.AchievementPicture/bytes/filename/mimetype",
                verbose_name="Imagem da Medalha",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Escondida?"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="users",
            field=models.ManyToManyField(
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="xp",
            field=models.IntegerField(default=100, verbose_name="Experiência"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(
                choices=[
                    ("unkwon", "Unkwon"),
                    ("c", "C"),
                    ("cplusplus", "C++"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("python", "Python"),
                ],
                default="unkwon",
                max_length=10,
            ),
        ),
    ]
