# Generated by Django 5.1.2 on 2024-11-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_achievement_badge_alter_achievement_hidden_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={
                "ordering": ("name",),
                "verbose_name": "Medalha",
                "verbose_name_plural": "Medalhas",
            },
        ),
    ]
