# Generated by Django 6.0.5 on 2026-05-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_achievement_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="badge_s3",
            field=models.ImageField(
                null=True, upload_to="achievements/", verbose_name="Imagem da Medalha"
            ),
        ),
    ]
