# Generated by Django 6.0.5 on 2026-05-26 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_migrate_achievement_badges_to_s3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="badge",
            new_name="badge_old",
        ),
    ]
