# Generated by Django 6.0.5 on 2026-05-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_rename_badge_achievement_badge_old_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="badge_s3",
            new_name="badge",
        ),
    ]
