# Generated by Django 6.0.5 on 2026-05-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_badge_s3_achievement_badge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="badge_old",
        ),
    ]
