# Generated by Django 3.2.4 on 2021-07-15 17:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0007_alter_submission_language")]

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Esperando ser executada."),
                            ("SintaxError", "Erro de sintaxe!"),
                            ("RuntimeError", "Erro em execução!"),
                            ("TimeoutError", "Tempo de execução excedido!"),
                            (
                                "DiffError",
                                "Saída computada diferente da saída esperada!",
                            ),
                            ("OK", "OK"),
                        ],
                        default="Waiting",
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("unkwon", "Unkwon"),
                            ("c", "C"),
                            ("c++11", "C++11"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("python", "Python"),
                        ],
                        default="unkwon",
                        max_length=10,
                    ),
                ),
                ("log", models.TextField(blank=True)),
                ("output", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
