# Generated by Django 3.2.4 on 2021-07-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="input",
            field=models.TextField(blank=True),
        ),
    ]
