# Generated by Django 5.1.2 on 2024-11-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_filecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecode",
            name="language",
            field=models.CharField(
                choices=[
                    ("unkwon", "Unkwon"),
                    ("c", "C"),
                    ("cplusplus", "C++"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("python", "Python"),
                ],
                default="unkwon",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="runner",
            name="language",
            field=models.CharField(
                choices=[
                    ("unkwon", "Unkwon"),
                    ("c", "C"),
                    ("cplusplus", "C++"),
                    ("javascript", "JavaScript"),
                    ("java", "Java"),
                    ("python", "Python"),
                ],
                default="unkwon",
                max_length=10,
            ),
        ),
    ]
