# Generated by Django 2.2.1 on 2019-06-10 14:28

from django.db import migrations, models
from statistics.models import StatisticsView


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsView",
            fields=[
                (
                    "username",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.IntegerField(editable=False)),
                ("xp", models.IntegerField(editable=False)),
                ("number_of_submissions_ok", models.IntegerField(editable=False)),
                ("number_of_submission", models.IntegerField(editable=False)),
                (
                    "conclusion_rate",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                (
                    "sucess_rate",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                (
                    "sintax_error_rate",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                (
                    "runtime_error_rate",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                (
                    "timeout_error_rate",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                (
                    "diff_error_rate",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "StatisticsView",
                "verbose_name_plural": "StatisticsView",
                "db_table": "statistics_view",
                "managed": False,
            },
        ),
        migrations.RunSQL(StatisticsView.SQL, StatisticsView.REVERSE_SQL),
    ]
