# Generated by Django 2.2.1 on 2019-06-10 15:17

from django.db import migrations, models
from statistics.models import SubmissionSummaryView


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_statisticsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSummaryView',
            fields=[
                ('status', models.CharField(editable=False,
                                            max_length=255, primary_key=True, serialize=False)),
                ('sum', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Summary of Submission',
                'verbose_name_plural': 'Summary of Submissions',
                'db_table': 'submission_summary_view',
                'managed': False,
            },
        ),
        migrations.RunSQL(SubmissionSummaryView.SQL,
                          SubmissionSummaryView.REVERSE_SQL)
    ]
