# Generated by Django 2.2.1 on 2019-06-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_submissionsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticsview',
            options={'managed': False, 'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
    ]
