# Generated by Django 3.0.8 on 2020-07-11 22:25

from django.db import migrations, models
from statistics.models import LeaderboardView


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_logrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='LeaderboardView',
            name='group',
            field=models.CharField(editable=False, max_length=255)
        ),
        migrations.RunSQL(LeaderboardView.SQL, LeaderboardView.REVERSE_SQL)
    ]
