# Generated by Django 4.2.7 on 2023-12-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics", "0007_remove_20231128_2151"),
    ]

    operations = [
        migrations.AddField(
            model_name="logrecord",
            name="ip",
            field=models.GenericIPAddressField(default="127.0.0.1", unpack_ipv4=True),
        ),
    ]
