# Generated by Django 2.2.1 on 2019-06-10 14:22

from django.db import migrations, models
from views.models import LeaderboardView


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardView',
            fields=[
                ('position', models.IntegerField(
                    editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(editable=False, max_length=255)),
                ('xp', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboard',
                'db_table': 'leaderboard_view',
                'managed': False,
            },
        ),
        migrations.RunSQL(LeaderboardView.SQL, LeaderboardView.REVERSE_SQL)
    ]
